title: Star Quiz
description: Are you a true fan of Star Wars ?
license:
  name: MIT
  url: https://github.com/BenSouchet/sorbus/blob/main/LICENSE
maintainers:
  - name: Ben Souchet
    url: https://github.com/BenSouchet
